var territorys = [
    "South East",
    "North East",
    "Mid Atlantic",
    "Mid West",
    "TOLA",
    "North West",
    "South West",
]
var territoryColors = {
    "South East":"yellow",
    "North East":"blue",
    "Mid Atlantic":"black",
    "Mid West":"green",
    "TOLA":"orange",
    "North West":"purple",
    "South West":"red",
}
var salesReps = {
    "South East":"TBH",
    "North East":"Lawrence Lanzilli",
    "Mid Atlantic":"Lawrence Lanzilli",
    "Mid West":"TBH",
    "TOLA":"David Vida",
    "North West":"David Vida",
    "South West":"David Vida",
}

var territoryStates = {
    "Alabama": "South East",
    "Alaska": "North West",
    "Arizona": "South West",
    "Arkansas": "TOLA",
    "California": "South West",
    "Colorado": "South West",
    "Connecticut": "North East",
    "Delaware": "Mid Atlantic",
    "District of Columbia": "South East",
    "Florida": "South East",
    "Georgia": "South East",
    "Hawaii": "South West",
    "Idaho": "North West",
    "Illinois": "Mid West",
    "Indiana": "Mid West",
    "Iowa": "Mid West",
    "Kansas": "Mid West",
    "Kentucky": "South East",
    "Louisiana": "TOLA",
    "Maine": "North East",
    "Maryland": "Mid Atlantic",
    "Massachusetts": "North East",
    "Michigan": "Mid West",
    "Minnesota": "Mid West",
    "Mississippi": "South East",
    "Missouri": "Mid West",
    "Montana": "North West",
    "Nebraska": "Mid West",
    "Nevada": "South West",
    "New Hampshire": "North East",
    "New Jersey": "Mid Atlantic",
    "New Mexico": "South West",
    "New York": "Mid Atlantic",
    "North Carolina": "South East",
    "North Dakota": "Mid West",
    "Ohio": "Mid West",
    "Oklahoma": "TOLA",
    "Oregon": "North West",
    "Pennsylvania": "Mid Atlantic",
    "Rhode Island": "North East",
    "South Carolina": "South East",
    "South Dakota": "Mid West",
    "Tennessee": "South East",
    "Texas": "TOLA",
    "Utah": "South West",
    "Vermont": "North East",
    "Virginia": "Mid Atlantic",
    "Washington": "North West",
    "West Virginia": "Mid Atlantic",
    "Wisconsin": "Mid West",
    "Wyoming": "North West",
    "Puerto Rico": "South East",
}